image: Visual Studio 2019

environment:
  PYTHON: C:\Python39

build: off  # Отключаем автоматическую сборку MSBuild

install:
  - pip install flask
  - pip install gunicorn
  - pip install requests

test_script:
  - st.bat
  - cd flaskapp
